### ISSUE TITLE
Is this package still maintained?

### ISSUE THREAD

**Issue by jiningq** [Keno/LSH.jl#1]
I'm just not sure since it has no update in almost a year. Is this package still maintained and in use, or is there somewhere else I should go for doing locality sensitive hashing in Julia?

Thanks!

**Comment by Keno** [comment]
I wrote this package for an algorithms class, but don't really have a use for it, so I haven't been working on it anymore. It's competitive with the reference implementation of LSH, probably usable and quite simple. However, don't expect a production package here, as I never intended it as such.

**Comment by jiningq** [comment]
Ok I understand. Thanks for your reply!
